name: dApp CI and SAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  SolLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: solhint
        run: npm install -g solhint
      - name: initialising solhint
        run: solhint --init
      - name: running lint on conratc
        run: solhint 'contracts/*.sol'
        
      - name: Cache node dependencies
        uses: actions/cache@v2
        id: node-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.node-cache.outputs.cache-hit != 'true' }}
        run: cd frontend && npm install
  SCA-and-SAST:
    needs: SolLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Scanning Nodejs project
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: 'frontend/'
          fail-build: true
          severity-cutoff: critical
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
          
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
  
      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        continue-on-error: true
        id: slither
        with:
          target: 'contracts/'
  Build-and-Test:
    needs: SCA-and-SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing truffle
        run: npm install -g truffle
 
      - name: Compiling the smart contract
        run: truffle compile

      - name: Run test cases
        run: truffle test
  UploadSmartContractArtifact:
    needs: Build-and-Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing truffle
        run: npm install -g truffle
 
      - name: Compiling the smart contract
        run: truffle compile

      - name: Archive smart-Contract artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SmartContract
          path: frontend/src/contracts
  UploaddAppArtifact:
    needs: UploadSmartContractArtifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        if: ${{ steps.node-cache.outputs.cache-hit != 'true' }}
        run: cd frontend && npm install
      
      - name: Archive dApp artifacts
        uses: actions/upload-artifact@v3
        id: dapp
        with:
          name: dApp
          path: |
             . 
             !frontend/node_modules
  Deploy:
    needs: UploaddAppArtifact
    runs-on: ubuntu-latest
    environment: staging
    steps:     
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: dApp
          run-id: dapp
        
      - name: listing file
        run: ls -al  

      - name: rsync
        uses: D3rHase/rsync-deploy-action@v0.2
        with:
          HOST: ${{ secrets.HOST}}
          PORT: ${{ secrets.SSH_PORT}}
          USER: ${{ secrets.USER_NAME}}
          PRIVATE_SSH_KEY: ${{ secrets.SSH_KEY}}
          REPOSITORY_PATH: .
          SERVER_PATH: /home/ubuntu/dApp
      
      
      - name: Running App on Server
        uses: appleboy/ssh-action@master
        with:
          script: |
            whoami
            cd /home/ubuntu/dApp/frontend
            npm install || echo $? && echo 0
            pm2 --name session1 start npm -- start
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER_NAME}}
          key: ${{ secrets.SSH_KEY}}

