name: dApp CI and SAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node dependencies
        uses: actions/cache@v2
        id: node-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: cd frontend && npm install

      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        continue-on-error: true
        id: slither
        with:
          target: 'contracts/'
