name: dApp CI and SAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - staging

jobs:
  CheckOut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node dependencies
        uses: actions/cache@v2
        id: node-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        run: cd frontend && npm install
  SCA-and-SAST:
    needs: CheckOut
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Scanning Nodejs project
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: 'frontend/'
          fail-build: true
          severity-cutoff: critical
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
          
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
  
      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        continue-on-error: false
        id: slither
        with:
          target: 'contracts/'
  Build-and-Test:
    needs: SCA-and-SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing truffle
        run: npm install -g truffle
 
      - name: Compiling the smart contract
        run: truffle compile

      - name: Run test cases
        run: truffle test
      

